# Generated by Django 5.0.7 on 2025-03-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='File',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
