# Generated by Django 5.0.7 on 2024-12-29 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0003_rename_pdffile_article_file_alter_article_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
