# Generated by Django 5.0.7 on 2024-12-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0004_article_creation_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="content",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="Image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="ProjectSubThemes",
            new_name="projectSubThemes",
        ),
        migrations.RemoveField(
            model_name="project",
            name="PDFfile",
        ),
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
