# Generated by Django 5.0.7 on 2024-12-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0005_rename_content_project_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="projectSubThemes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
