# Generated by Django 5.0.7 on 2024-12-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0006_alter_project_projectsubthemes"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_base64",
            field=models.TextField(blank=True, null=True),
        ),
    ]
