# Generated by Django 5.0.7 on 2024-12-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0007_article_image_base64"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_base64",
            field=models.TextField(blank=True, null=True),
        ),
    ]
